name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Show runner resources
        run: |
          echo "CPU Info:"
          lscpu
          echo "Memory Info:"
          free -m

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build 
        run: cargo build --all --locked --jobs 1

      - name: Run tests
        run: cargo test --all -- --nocapture --test-threads=1

      - name: Show memory/CPU usage after tests
        if: always()
        run: |
          echo "Memory Info after tests:"
          free -m
          echo "Top 10 memory-consuming processes:"
          ps aux --sort=-%mem | head -n 10
