name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check
        run: cargo check --all-targets

      - name: Run tests
        timeout-minutes: 15
        run: cargo test --all -- --nocapture --test-threads=1
        env:
          RUST_BACKTRACE: full

      - name: Clippy check
        run: cargo clippy --all-targets -- -D warnings

      - name: Rustfmt check
        run: cargo fmt -- --check